### ISSUE TITLE
Front end issues

### ISSUE THREAD

**Issue by jgatjens** [franticnoise/photosearch#4]
Issues (index.html)
 
- Logo and Arrow need to be inline SVGs
- Header should be center.
- we need a link on the arrow to search.html

Issues(search.html)

- The arrow is again pixelated.
- Margin between search input and the title "all results" is different.
- Margin between images on the grid is different as well.
- footer should be aligned to the bottom of the page.

**Comment by franticnoise** [comment]
### final fine tuned css deploy
- fixed index.html issues with vertical and horizontal alignment, also added footer element.
- fixed all the margin and padding issues from search.html and itemdetail html files
- used a lot more of the tailwind syntax for specific margins, gaps, paddings such as  ```p-[15px]``` 
- replaced all the png arrows and logos with svg code 
- made href links for all the arrows to be able to navigate the site properly
- fixed the footer element to the bottom of the viewport with the classes ``` fixed -inset-x-15 ```
